Editor plugin login fix
RallyHereInteractive/unreal-plugins pull request #232
Opened 2024-06-05 14:33 UTC by minuileee

Fixed the login issue by getting the access token using the auth code.

2024-06-05 15:39 UTC, hirez-cranney commented
The templates in openapi-generator-rh-cpp-unreal need to be updated so that they generate the proper version of the auth context changes (since that file is generated)

2024-06-13 19:04 UTC, rallyhere-cranney commented on RallyHereDeveloperAPI/Source/RallyHereDeveloperAPI/Public/RallyHereDeveloperAPIAuthContext.h
> +    FString GetClientId() const;
Preferably this would return the actual TOptional<FString>, so that when it is not set, it can return an empty optional rather than an empty string.

2024-06-13 19:08 UTC, rallyhere-cranney requested changes
The client id accessor on the auth context should use an optional (it is currently stored that way, but is not returned as an optional).  That will have a few knock on changes.

Otherwise, looks good.

2024-06-18 18:38 UTC, rallyhere-cranney commented
@minuileee in the last commit it looks like the mustache files for the autogenerator were updated, but not the files they generate.  Can you also add those?  Should be good after that.

2024-06-18 19:05 UTC, minuileee commented
I was dumb, forgot to commit those files. My bad

2024-06-18 21:00 UTC, rallyhere-cranney approved these changes

2024-06-18 21:01 UTC, merged